### ISSUE TITLE
Missing "moment-timezone" dependancy

### ISSUE THREAD

**Issue by tomerb15** [wix/availability4js#1]
1. Install this npm on a nodeJS server
2. require it somewhere (E.G var availability = require('availability'))
3. Exception - Missing the "moment-timezone" module.

I fixed it by installing moment-timezone separately on my server, but you should add it as a dependancy.

**Comment by dleshem** [comment]
Fixed in https://github.com/wix/availability4js/commit/979dbed66f543e09b788bb6c29bd2e51f837f846, new version live in npmjs.
